config/routes.rb
FitnessSchedules::Application.routes.draw do
  get "reports/new"

  get "reports/show"

  get "schedules/new"

  resources :trainers
  resources :clients do
  	member do
  		get 'add_trainer'
  		get 'remove_trainer'
  	end
  end
  resources :sessions
  resources :schedules do
  	member do
  		put 'complete'
  		get 'duplicate'
  	end
  end
  resources :reports
  
  match '/signin', to: "sessions#new"
  match '/signout', to: "sessions#destroy", via: :delete
  
  match '/noauth', to: redirect('/NotAuth.html')
  
  root to: "static_pages#home"

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  attr_accessible :rendered, :scheduled_date, :trainer_id, :exercises_attributes
  
  belongs_to :client
  belongs_to :trainer
  has_many :exercises
  accepts_nested_attributes_for :exercises, allow_destroy: true
  
  validates :client_id, presence: true
  validates :trainer_id, presence: true
  validates :scheduled_date, presence: true
  validates :scheduled_date, date: { after: Proc.new { (Date.yesterday) } }, on: :create
  
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  	
  before_filter :trainer_only, only: [:edit, :update]
  before_filter :schedule_owner
  before_filter :rendered, only: [:edit, :update]
  	
  def show
  	@schedule = Schedule.find(params[:id])
  end
  
  def duplicate
    schedule = Schedule.find(params[:id])
    new_schedule = schedule.dup
    new_schedule.scheduled_date = Date.today
    new_schedule.rendered = nil
    new_schedule.exercises << schedule.exercises.collect { |ex| ex.dup }
    new_schedule.save
    redirect_to edit_schedule_path(new_schedule)
  end
  
  def edit
  	@schedule = Schedule.find(params[:id])
  end
  
  def update
		@schedule = Schedule.find(params[:id])
    if @schedule.update_attributes(params[:schedule])
      flash[:notice] = "Successfully added exercise"
      redirect_to @schedule
    else
      render 'edit'
    end
	end
	
	def complete
		@schedule = Schedule.find(params[:id])
		true_client = @schedule.client
		auth_client = Client.find_by_email(params[:schedule][:client][:email])
		if params[:schedule][:rendered] == nil
			flash[:alert] = "Must choose an option"
			redirect_to @schedule
		elsif true_client == auth_client && auth_client.authenticate(params[:schedule][:client][:password])
			@schedule.rendered = params[:schedule][:rendered]
			@schedule.save
			redirect_to client_path(true_client)
		else
			flash[:alert] = "Incorrect client authentication"
			redirect_to @schedule
		end
	end
	
end

app/helpers/schedules_helper.rb
module SchedulesHelper

  def schedule_complete(schedule)
    if schedule.rendered == true
      "| Completed"
    elsif schedule.rendered == false
      "| Cancelled (within 24 hours)"
    else
      nil
    end
  end
  
  def rendered
    schedule = Schedule.find(params[:id])
    unless schedule.rendered == nil
      flash[:alert] = "This schedule is marked as complete and cannot be edited"
      redirect_to schedule 
    end
  end
  
  def add_trainer_id_to_new_schedule
    params[:client][:schedules_attributes].first[1][:trainer_id] = current_user.id
  end
  
end

app/views/schedules/complete.html.erb
<% provide(:title, "Complete Schedule") %>
<h2> Complete </h2>

<%= params %>

	

app/views/schedules/edit.html.erb
<% provide(:title, @schedule.scheduled_date) %>

<section class="session">
	<h2>Workout for <%= link_to @schedule.client.name, schedule_path(@schedule) %></h2>
	<h3><%= @schedule.scheduled_date.strftime("%A, %B %e, %Y") %></h3>
	
	<%= render :partial => 'shared/errors', :locals => { :user => @schedule } %>
	
	<%= nested_form_for @schedule do |f| %>

		<div class="buttons">
			<%= f.submit "Save", :class => 'save' %>
			<%= link_to "Cancel", @schedule, :class => 'cancel' %>
		</div>
	
		<p><%= f.link_to_add "Add Exercise", :exercises %></p>
			
		<%= f.fields_for :exercises do |exercise_form| %>
			<%= exercise_form.label :circuit %>
			<%= exercise_form.number_field :circuit, { min: 1, step: 1 } %>
			<br>		
			<%= exercise_form.label :ex_order, "Order" %>
			<%= exercise_form.number_field :ex_order, { min: 1, step: 1 } %>
			<br>
			<%= exercise_form.label :name %>
			<%= exercise_form.text_field :name %>
			<br>
			<%= exercise_form.label :weight_or_intensity, "Weight/Intensity" %>
			<%= exercise_form.text_field :weight_or_intensity %>
			<br>
			<%= exercise_form.label :reps_or_duration, "Reps/Duration" %>
			<%= exercise_form.text_field :reps_or_duration %>
			<br>
			<%= exercise_form.label :comments, "Comments" %>
			<%= exercise_form.text_area :comments %>
			<br>
			<%= exercise_form.link_to_remove "Remove Exercise" %>
		<% end %>
		
		<div class="buttons">
			<%= f.submit "Save", :class => 'save' %>
			<%= link_to "Cancel", @schedule, :class => 'cancel' %>
		</div>
	<% end %>
</section>

app/views/schedules/new.html.erb
<% provide(:title, "Create new schedule") %>

<%= render :partial => 'shared/errors', :locals => { :user => @schedule } %>


<% end %>


	
	

app/views/schedules/show.html.erb
<% provide(:title, @schedule.scheduled_date) %>

<section class="session">
	<h2>Workout for <%= link_to(@schedule.client.name, client_path(@schedule.client)) %></h2>
	<h3><%= @schedule.scheduled_date.strftime("%A, %B %e, %Y") %></h3>
  <%= link_to "Clone Schedule", controller: "schedules", action: "duplicate", id: @schedule.id %>
	<% if session[:user_class] == Trainer && @schedule.rendered.nil? %>
		<%= link_to 'Edit Session', edit_schedule_path(@schedule), :class => "edit_session" %>
	<% end %>
	
	<table class="workout_summary">
		<thead>
			<tr>
				<td>Circuit</td>
				<td>Order</td>
				<td>Exercise</td>
				<td>Weight or Intensity</td>
				<td>Reps or Duration</td>
				<td>Comments</td>
			</tr>
		</thead>
		<tbody>
		<% if !@schedule.exercises.empty?
			@schedule.exercises.order(:circuit, :ex_order).each do |exercise| %>
	  	<tr>
	    	<td><%= exercise.circuit %></td>
	    	<td><%= exercise.ex_order %></td>
	    	<td><%= exercise.name %></td>
	    	<td><%= exercise.weight_or_intensity %></td>
	    	<td><%= exercise.reps_or_duration %></td>
	    	<td><%= exercise.comments %></td>
	  	</tr>
	  <%	end
		  else
	  %>
	  	<tr><td colspan="6">No circuits recorded yet.</td></tr>
	  <% end %>
	  </tbody>
	</table>

	
	<% if @schedule.rendered.nil? %>
		<h3>Indicate completion of this session</h3>
		<%= form_for @schedule, :url => complete_schedule_path(@schedule) do |f| %>
		
		<div class="row">
			<%= f.radio_button :rendered, true %>
			<%= f.label :rendered, "I received this training session on the scheduled date.", :value => true %>
		</div>
		<div class="row">
			<%= f.radio_button :rendered, false %>
			<%= f.label :rendered, "I cancelled this training session with less than 24 hours notice.", :value => false %>
		</div>
			
			<%= f.fields_for @schedule.client do |client_fields| %>
		<div class="row">
				<%= client_fields.label :email %>
				<%= client_fields.text_field :email %>
		</div>
		<div class="row">
				
				<%= client_fields.label :password %>
				<%= client_fields.password_field :password %>
		</div>
			<% end %>
			
			<%= f.submit "Submit", :class => "save" %>
		
		<% end %>
	
	<% end %>
</section>