config/routes.rb
FitnessSchedules::Application.routes.draw do
  get "reports/new"

  get "reports/show"

  get "schedules/new"

  resources :trainers
  resources :clients do
  	member do
  		get 'add_trainer'
  		get 'remove_trainer'
  	end
  end
  resources :sessions
  resources :schedules do
  	member do
  		put 'complete'
  		get 'duplicate'
  	end
  end
  resources :reports
  
  match '/signin', to: "sessions#new"
  match '/signout', to: "sessions#destroy", via: :delete
  
  match '/noauth', to: redirect('/NotAuth.html')
  
  root to: "static_pages#home"

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation, :schedules_attributes
  has_secure_password
  has_many :relationships
  has_many :trainers, through: :relationships
  has_many :schedules
  
  accepts_nested_attributes_for :schedules, allow_destroy: true
  
  validates :name, presence: true, length: { maximum: 40 }
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :password_confirmation, presence: true, length: { minimum: 6 }, on: :create
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  					uniqueness: { case_sensitive: false }, on: :create
	
	before_save { |client| client.email = email.downcase }
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	before_filter :signed_in_user, only: [:show, :index]
	before_filter :trainer_only, only: [:index, :edit, :update]
	before_filter :profile_owner, only: [:show, :edit, :update]
	
  def new
  	@client = Client.new
  end
  
  def create
  	@client = Client.new(params[:client])
  	if @client.save
  		flash[:success] = "Account created successfully"
  		redirect_to client_path(@client)
  	else
  		render 'new'
  	end
  end
  
  def show
  	@client = Client.find(params[:id])
  end
  
  def index
  	@clients = Client.paginate(:page => params[:page])
  end
	
	def edit
		@client = Client.find(params[:id])
	end
	
	def update
		@client = Client.find(params[:id])
		add_trainer_id_to_new_schedule
		if @client.update_attributes(params[:client])
			flash[:notice] = "Successfully added schedule"
			redirect_to @client
		else
			render 'edit'
		end
	end
	
	def add_trainer
		client = Client.find(params[:id])
		current_user.clients << client
		redirect_to client_path(client)
	end
	
	def remove_trainer
		client = Client.find(params[:id])
		current_user.clients.delete(client)
		redirect_to trainer_path(current_user)
	end
	
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_add_client_to_trainer.html.erb
<%= form_for @client do |f| %>
<%= f.hidden_field @client.id %>
<%= f.submit 'Add Client' %>

app/views/clients/_list_clients.erb
<%= will_paginate @clients %>
<ul class="clients"><% @clients.order(:name).each do |client| %>
	<li class="<%= client.trainers.include?(current_user) ? " training" : client.trainers == [] ? "" : " disabled" %>">
	<%- if session[:user_class] == Trainer
	  		if client.trainers.include? current_user %>
	  	<%= link_to client.name, client_path(client), :class => "client" %>
		<div class="options">
			<%= link_to "Sessions", edit_client_path(client), :class => "schedule" %>
			<%= link_to "Remove", remove_trainer_client_path(client), :confirm => "Are you sure you wish to remove " + client.name + " as a client?", :class => "remove" %>
		</div>
	<%- 	else %>
		<h3 class="client"><%= client.name %></h3>
		<div class="options">
			<%= link_to "Train", add_trainer_client_path(client), :class => "train" %> 
		</div>
	<%-		end
		else %>
			<h3 class="client"><%= client.name %></h3>
	<%- end %>
	</li>
<% end %></ul>

app/views/clients/edit.html.erb
<% provide(:title, @client.name) %>

<section class="client">
	<h2><%= link_to @client.name, @client %></h2>
	
	<%= render :partial => 'shared/errors', :locals => { :user => @client } %>
	
	<%= nested_form_for @client do |f| %>
		<div class="buttons">
			<%= f.submit "Save", :class => 'save' %>
			<%= link_to "Cancel", @client, :class => "cancel", :confirm => "Are you sure you wish to cancel? All unsaved changes will be lost." %>
		</div>
		<div id="add_sessions">
			<%= f.link_to_add "Add Session", :schedules, :class => "add_session" %>
		</div>
		<h3>Current Sessions:</h3>
		<div id="current_sessions">
			<%= f.fields_for :schedules do |schedule_form| %>
				<div class="row">
          <%= schedule_form.object.trainer_id == current_user.id ? "Schedule owned by you" : "Scheduled not owned by you" %>
					<div class="date_select_block">
						<%= schedule_form.date_select :scheduled_date, { :order => [:month, :day, :year] }, :class => "date_select" %>
					</div>
					<%= schedule_form.link_to_remove "Remove", :class => "remove" %>
					<%= schedule_form.hidden_field :trainer_id %>
					<%= hidden_field_tag :trainer_id %>
				</div>
			<% end %>
		</div>
	
		<div class="buttons">
			<%= f.submit "Save", :class => 'save' %>
			<%= link_to "Cancel", @client, :class => "cancel", :confirm => "Are you sure you wish to cancel? All unsaved changes will be lost." %>
		</div>
	<% end %>
</section>

app/views/clients/index.html.erb
<% provide(:title, 'All Clients') %>

<%= render :partial => 'clients/list_clients' %>

app/views/clients/new.html.erb
<% provide(:title, "Create new client account") %>

<%= render :partial => 'shared/errors', :locals => { :user => @client } %>
<%= render :partial => 'shared/new_user_form', :locals => { :user => @client } %>

app/views/clients/show.html.erb
<% provide(:title, @client.name) %>
<section class="client">
	<h2><%= yield(:title)%></h2>
	
	<% if session[:user_class] == Trainer %>
	<%= link_to "Edit Sessions", edit_client_path(@client), :class => "edit_sessions" %>
	<% end %>
	
	<ul class="client_sessions"><% @client.schedules.order("scheduled_date DESC").each do |schedule| %>
		<li><%= link_to schedule.scheduled_date.strftime("%B %d, %Y"), schedule_path(schedule), :class => "session" %> with <%= schedule.trainer.name %> <%= schedule_complete(schedule) %></li>
	<% end %></ul>
</section>