config/routes.rb
FitnessSchedules::Application.routes.draw do
  get "reports/new"

  get "reports/show"

  get "schedules/new"

  resources :trainers
  resources :clients do
  	member do
  		get 'add_trainer'
  		get 'remove_trainer'
  	end
  end
  resources :sessions
  resources :schedules do
  	member do
  		put 'complete'
  		get 'duplicate'
  	end
  end
  resources :reports
  
  match '/signin', to: "sessions#new"
  match '/signout', to: "sessions#destroy", via: :delete
  
  match '/noauth', to: redirect('/NotAuth.html')
  
  root to: "static_pages#home"

end

app/views/layouts/_footer.html.erb
<footer>
	<a href="http://thesportsclubla.com" rel="external" class="club_link">The Sports Club/LA</a>
</footer>

app/views/layouts/_header.html.erb
<header>
		<h1>
			Fitness Tracker <%# Seems like at some point we'll need a catchy name. For now, I'm just trying to shorten this and remove SCLA reference (so RSCNY can use it) %>
		</h1>
		<nav>
		
			<%# Added logic for styling buttons to show what page the user is on %>
		<% if signed_in? %>
			<% if session[:user_class] == Trainer %>
				<%= link_to "My Profile", trainer_path(Trainer.find(session[:user_id])), :class => (current_page?(trainer_path(Trainer.find(session[:user_id]))) ? "selected" : "") %>
				<%= link_to "Client Index", clients_path, :class => (current_page?(clients_path) ? "selected" : "") %>
					<% if current_user.admin == true %>
					  <%= link_to "Create New Trainer", new_trainer_path %>
					  <%= link_to "Reports", new_report_path %>
					<% end %>
			<% elsif session[:user_class] == Client %>
				<%= link_to "My Profile", client_path(Client.find(session[:user_id])), :class => (current_page?(client_path(Client.find(session[:user_id]))) ? "selected" : "") %>
			<%# else
				# Why a sign in link when they're already supposedly signed-in?
				# If they're signed in, but not a Trainer or a Client, something's clearly wrong…
				# But why provide a sign-in? Shouldn't they sign out first either way? 
				# <%= link_to "Sign in", signin_path %>
			<% end %>						
			<%= link_to "Sign out", signout_path, method: "delete", :class => "signout" %>
		<% else %>
			<%= link_to "Home", root_path, :class => (current_page?(root_path) || current_page?('/') ? "selected" : "") %>
			<%= link_to "Sign in", signin_path, :class => (current_page?(new_session_path) || current_page?('/signin') || current_page?('/sessions') ? "selected" : "")  %>
		<% end %>

		</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application-screen",	:media => "screen" %>
  <%= stylesheet_link_tag    "application-print",	:media => "print" %>
  <!--[if lte IE 8]>
  	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  	<%= stylesheet_link_tag    "application-ie",		:media => "all" %>
  <![endif]-->
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width" />
</head>
<body>
<%= render 'layouts/header' %>
<div id="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
</div>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>